CREATE TABLE workout (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text NOT NULL
);

CREATE TABLE exercise (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE workout_exercise (
    workout_id integer,
    exercise_id integer,
    reps integer,
    sets integer,
    PRIMARY KEY (workout_id, exercise_id),
    FOREIGN KEY (workout_id) REFERENCES workout(id),
    FOREIGN KEY (exercise_id) REFERENCES exercise(id)
);

CREATE TABLE historical_data (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id integer,
    exercise_id integer,
    reps integer,
    set_number integer,
    weight DECIMAL(10, 2),
    created timestamp with time zone NOT NULL,
    FOREIGN KEY (workout_id) REFERENCES workout(id),
    FOREIGN KEY (exercise_id) REFERENCES exercise(id)
);

INSERT INTO workout(name, description)
    VALUES 
        ('A', 'hypertrophy'),
        ('B', 'hypertrophy');

INSERT INTO exercise(name)
VALUES 
    ('Skullcrusher'),
    ('Bench Press'),
    ('Squat'),
    ('Deadlift'),
    ('Barbell Curl'),
    ('Tricep Dip'),
    ('Leg Press'),
    ('Shoulder Press'),
    ('Pull-up'),
    ('Push-up'),
    ('Plank'),
    ('Leg Curl'),
    ('Sit-up'),
    ('Lat Pulldown'),
    ('Rowing Machine'),
    ('Bicep Curl'),
    ('Lunge'),
    ('Burpee'),
    ('Mountain Climber'),
    ('Box Jump');

INSERT INTO workout_exercise (workout_id, exercise_id, reps, sets)
VALUES
    (1, 1, 12, 3), -- Skullcrusher in Workout A
    (1, 2, 10, 3), -- Bench Press in Workout A
    (1, 3, 8, 3),  -- Squat in Workout A
    (2, 4, 5, 5),  -- Deadlift in Workout B
    (2, 5, 10, 4); -- Barbell Curl in Workout B

INSERT INTO historical_data (workout_id, exercise_id, reps, set_number, weight, created)
VALUES
    (1, 1, 12, 1, 25.0, '2024-05-18 09:00:00+00'), -- First set of Skullcrusher, 25kg
    (1, 1, 12, 2, 25.0, '2024-05-18 09:05:00+00'), -- Second set of Skullcrusher, 25kg
    (1, 1, 12, 3, 25.0, '2024-05-18 09:10:00+00'), -- Third set of Skullcrusher, 25kg
    (2, 4, 5, 1, 100.0, '2024-05-19 09:00:00+00'), -- First set of Deadlift, 100kg in Workout B
    (2, 4, 5, 2, 100.0, '2024-05-19 09:05:00+00'); -- Second set of Deadlift, 100kg in Workout B


-- Grant permissions to all tables in a specific schema
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ruud;

